version: 0.0

Resources:

  - TargetService:

      Type: AWS::ECS::Service

      Properties:

        TaskDefinition: "arn:aws:ecs:us-east-2:504649076991:task-definition/ahmad-taskdef-terra:76"

        LoadBalancerInfo:

          ContainerName: "nginx-terra"

          ContainerPort: 80
